### ISSUE TITLE
It Does not import skp file even box shape objects. and also cant remove that plugin in blender

### ISSUE THREAD

**Issue by ashwin0014** [arindam-m/pyslapi#10]
**Describe the bug**

**To Reproduce**
3. See error (if any) 'Error Log: ....'

**Expected behavior**

**Screenshots**
[To attach a file to an issue, drag and drop it into the comment box]

**System Info**
 - Operating System: [e.g. Windows 10]
 - Blender Version [e.g. 2.82a] (Only official releases)
 - SketchUp Version [e.g. 2019]
 - Importer Version [eg. v.0.20.2]

**Additional context**

**Comment by arindam-m** [comment]
Insufficient info.
