### ISSUE TITLE
Feature request: a Linux version

### ISSUE THREAD

**Issue by Shaddy-ElDesouky** [arindam-m/pyslapi#14]
@arindam-m  Please consider a Linux version, or if it is impossible please tell us so we stop trying and save time :)

**Comment by rdrockz** [comment]
Hi @arindam-m Dada. I second the linux request. Or kindly tell us how to build for the same. 🙂

**Comment by cybergrunge-ops** [comment]
also would like this

**Comment by schue** [comment]
It is possible to run this importer on Linux using the devel version of WINE. You have to install SketchUp because the importer actually uses parts of SketchUp in a library form to read the .skp file.

**Comment by arindam-m** [comment]
Sketchup's C APIs and binaries (for Import/Export) are available only for Windows and macOS.

Read more about it [here](https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/index.html).

---
##### _With my current knowledge and skills, I am not sure how to make it portable and work on a Linux kernel as well._
