### ISSUE TITLE
Blender 2.9 support

### ISSUE THREAD

**Issue by 18883234348** [arindam-m/pyslapi#18]
Thank you for bringing us such an amazing plugin, but we need you to improve this plugin even more, for example with the released version 2.9 of blender.

**Comment by a4jp-com** [comment]
Can you update the plugin so it works in 2.91.2 please? This plugin is wonderful and was working in the older version. I'm not sure why it isn't working now though.

**Comment by arindam-m** [comment]
Check out this [release](https://github.com/arindam-m/pyslapi/releases/tag/v0.23.0) for Blender 2.93.x
