### ISSUE TITLE
Can`t import great skp files to blender. I work with blender 2.9 and sketchup pro2021. I have installed the  import-export plug-iand it works with small files. Is there any limit of the filesize?

### ISSUE THREAD

**Issue by bertinger** [arindam-m/pyslapi#21]
**Describe the bug**

**To Reproduce**
3. See error (if any) 'Error Log: ....'

**Expected behavior**

**Screenshots**
[To attach a file to an issue, drag and drop it into the comment box]

**System Info**
 - Operating System: [e.g. Windows 10]
 - Blender Version [e.g. 2.82a] (Only official releases)
 - SketchUp Version [e.g. 2019]
 - Importer Version [eg. v.0.20.2]

**Additional context**

**Comment by ursulik88** [comment]
Hi
is possible to inport sketchup files in blender with groups and subgroups?

**Comment by RLGL1** [comment]
I have Sketchup Pro 2021 Blender 2.92. It appears the importer is a one and done .  Worked once, closed blender and reopened, attempt to import another  .skp nada no  one home. I tried to remove it with the following error:  
![2021-04-21_20-24-26](https://user-images.githubusercontent.com/73186170/115642170-12664b80-a2e0-11eb-9599-e917cef592fa.png)
4-21-21

**Comment by arindam-m** [comment]
Check out this [release](https://github.com/arindam-m/pyslapi/releases/tag/v0.23.0) for importing files from SketchUp 2021 or need to use Blender 2.93.x
