### ISSUE TITLE
As blender 2.93 is on the way, which is a LTS release, please update the code to support version 2.93. As due to some reasons it dont work in 2.93. And perhaps the idea to preserve sketchup group in blender would be great.

### ISSUE THREAD

**Issue by arcdipesh** [arindam-m/pyslapi#23]
**Describe the bug**

**To Reproduce**
3. See error (if any) 'Error Log: ....'

**Expected behavior**

**Screenshots**
[To attach a file to an issue, drag and drop it into the comment box]

**System Info**
 - Operating System: [e.g. Windows 10]
 - Blender Version [e.g. 2.82a] (Only official releases)
 - SketchUp Version [e.g. 2019]
 - Importer Version [eg. v.0.20.2]

**Additional context**

**Comment by RedHaloStudio** [comment]
https://github.com/RedHaloStudio/Sketchup_Importer/releases/tag/0.22.3

**Comment by arindam-m** [comment]
Check out this [release](https://github.com/arindam-m/pyslapi/releases/tag/v0.23.0) for Blender 2.93.x
