### ISSUE TITLE
Can't activate the addon in Blender 2.93

### ISSUE THREAD

**Issue by Allard888** [arindam-m/pyslapi#26]
I can install the latest version of the addon, but I can't activate it. The tickbox doesnt let me tick it.  It just stays empty when I click it. 

**To Reproduce**
1. Go to preferences
2. install the addon zipfile

**Expected behavior**
A tick should appear that activates the addon

**Screenshots**
[To attach a file to an issue, drag and drop it into the comment box]

**System Info**
 - Windows 10 64 bit fully updates
 - Blender Version 2.93
 - SketchUp Version [e.g. 2021
 - Importer Version = SketchUp_Importer_v0.21.1_Windows_x64

**Comment by odil24** [comment]
> I can install the latest version of the addon, but I can't activate it. The tickbox doesnt let me tick it. It just stays empty when I click it.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to preferences
> 2. install the addon zipfile
> 
> **Expected behavior**
> A tick should appear that activates the addon
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> [To attach a file to an issue, drag and drop it into the comment box]
> 
> **System Info**
> 
> * Windows 10 64 bit fully updates
> * Blender Version 2.93
> * SketchUp Version [e.g. 2021
> * Importer Version = SketchUp_Importer_v0.21.1_Windows_x64

Hi. Yes. It is normal behavour. Thats why this guy updated up to 0.22.x version. Here you can download zip file:
https://github.com/RedHaloStudio/Sketchup_Importer/releases/tag/0.22.3

**Comment by Allard888** [comment]
Ah yes, its working with the version you suggested..thank you!

**Comment by ericardos** [comment]
Mesmo coma versão do link, 0.22.3 não funcionou aqui. Uso blender no linux, será que só funciona no windows esse addon?

**Comment by arindam-m** [comment]
Check out this [release](https://github.com/arindam-m/pyslapi/releases/tag/v0.23.0) for Blender 2.93.x

**Comment by odil24** [comment]
Or also this too:
https://github.com/RedHaloStudio/Sketchup_Importer/releases/tag/0.22.4
