### ISSUE TITLE
0.22.3 File Importer Does Not  Import the desired File

### ISSUE THREAD

**Issue by RLGL1** [arindam-m/pyslapi#27]
**Describe the bug**

The file importer does not work.

**To Reproduce**

Open Blender
Attempt to import the 2021 SketchUp file using the importer version 0.22.3

**Expected behavior**

The file should be imported

System Info

Operating System: Windows 10 20H2 19042.928
Blender Version 2.92
SketchUp Version 2021 Pro 21.0.391
Importer Version 0.22.3

Additional context

If I save the same file down to the 2020 SketchUp Pro version it will import the way it should. The SketchUp 22021 file structure has changed. Among them the file size is reduced by about half.
 -
 - Blender Version  2.93.0
 - 
 - SketchUp Version  2021 Pro
 - 
 - Importer Version  0.22.3

**Additional context**

There are no errors when the add-on is installed or on the file import.
[Sample 2021 file.zip](https://github.com/arindam-m/pyslapi/files/6604296/Sample.2021.file.zip)

**Comment by arindam-m** [comment]
Check out this [release](https://github.com/arindam-m/pyslapi/releases/tag/v0.23.0) for importing files from SketchUp 2021 or need to use Blender 2.93.x
