### ISSUE TITLE
2.93 is not working at all

### ISSUE THREAD

**Issue by basarchitects** [arindam-m/pyslapi#28]
**Describe the bug**
the addon is not working on 2.93

**To Reproduce**
1. Go to 'preferences'
2. Click on 'add-ons'
3. Deactivate the add-on 
4. reactivate but it doesn't budge

**Expected behavior**

**Screenshots**
[To attach a file to an issue, drag and drop it into the comment box]

**System Info**
 - Operating System: [e.g. Windows 10]
 - Blender Version [e.g. 2.82a] (Only official releases)
 - SketchUp Version [e.g. 2019]
 - Importer Version [eg. v.0.20.2]

**Additional context**

**Comment by odil24** [comment]
> 
> 
> **Describe the bug**
> the addon is not working on 2.93
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Go to 'preferences'
> 
>     2. Click on 'add-ons'
> 
>     3. Deactivate the add-on
> 
>     4. reactivate but it doesn't budge
> 
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> [To attach a file to an issue, drag and drop it into the comment box]
> 
> **System Info**
> 
>     * Operating System: [e.g. Windows 10]
> 
>     * Blender Version [e.g. 2.82a] (Only official releases)
> 
>     * SketchUp Version [e.g. 2019]
> 
>     * Importer Version [eg. v.0.20.2]
> 
> 
> **Additional context**
> Add any other context about the problem here.

https://github.com/RedHaloStudio/Sketchup_Importer/releases/tag/0.22.3

**Comment by passivedragon** [comment]
Bumped, same issue. Add-on does not turn on, no message is produced

Blender version 2.93.1
importer version 0.21

**Comment by Caleidocane** [comment]
If you check the console this is the output "addon not found: 'SketchUp_Importer'"

**Comment by arindam-m** [comment]
Check out this [release](https://github.com/arindam-m/pyslapi/releases/tag/v0.23.0) for Blender 2.93.x
