### ISSUE TITLE
It'd be great if there is some kind of support for Linux Blender build ??

### ISSUE THREAD

**Issue by Zorono** [arindam-m/pyslapi#30]

**Comment by thhart** [comment]
Related: https://github.com/arindam-m/pyslapi/issues/14

**Comment by arindam-m** [comment]
Sketchup's C APIs and binaries (for Import/Export) are available only for Windows and macOS.

Read more about it [here](https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/index.html).
