### ISSUE TITLE
Doesn't work with Blender 2.9.3.1

### ISSUE THREAD

**Issue by ryandang1234** [arindam-m/pyslapi#31]
**Describe the bug**
After installed in Blender preferences, It doesn't allow me to enable the addon
Tried again with Blender 2.82 and it works fine, and allow me to enable it.

**To Reproduce**
1. preferences
2. install addon
3. wont allow to enable

**Expected behavior**
Is there a way to fix this? Is this a bug or something?

**System Info**
 - Operating System: Windows 10
 - Blender Version 2.9.3.1
 - SketchUp Version 2019
 - Importer Version 0.21

**Comment by odil24** [comment]
> **Describe the bug**
> After installed in Blender preferences, It doesn't allow me to enable the addon
> Tried again with Blender 2.82 and it works fine, and allow me to enable it.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. preferences
> 2. install addon
> 3. wont allow to enable
> 
> **Expected behavior**
> Is there a way to fix this? Is this a bug or something?
> 
> **System Info**
> 
> * Operating System: Windows 10
> * Blender Version 2.9.3.1
> * SketchUp Version 2019
> * Importer Version 0.21
Dont know exactly, but @arindam-m doesnt working on the project I think. @redhalostudio has been already released v0.22.3 for Blender 2.93: @https://github.com/RedHaloStudio/Sketchup_Importer/releases/tag/0.22.3

**Comment by seemon2** [comment]
Hi,
I have the same problem with latest version of Blender 2.9.3.0
Any help please?

**Comment by RedHaloStudio** [comment]
> Hi,
> I have the same problem with latest version of Blender 2.9.3.0
> Any help please?

https://github.com/RedHaloStudio/Sketchup_Importer/releases/tag/0.22.3

**Comment by XemarXe** [comment]
Same problem here blender 2.9.3.1 on Windows 10 64 bit

**Comment by fpibbs** [comment]
> > Hi,
> > I have the same problem with latest version of Blender 2.9.3.0
> > Any help please?
> 
> https://github.com/RedHaloStudio/Sketchup_Importer/releases/tag/0.22.3

Solved with this...

**Comment by Kwinkris** [comment]
> > > Hi,
> > > I have the same problem with latest version of Blender 2.9.3.0
> > > Any help please?
> > 
> > 
> > https://github.com/RedHaloStudio/Sketchup_Importer/releases/tag/0.22.3
> 
> Solved with this...

@fpibbs Thank you very much. It work ! 
I use it with Blender 2.93.2 on Windows 10 64bit
/ but have to save SKP back V2020 in order to import

**Comment by RedHaloStudio** [comment]
> > > > Hi,
> > > > I have the same problem with latest version of Blender 2.9.3.0
> > > > Any help please?
> > > 
> > > 
> > > https://github.com/RedHaloStudio/Sketchup_Importer/releases/tag/0.22.3
> > 
> > 
> > Solved with this...
> 
> @fpibbs Thank you very much. It work !
> I use it with Blender 2.93.2 on Windows 10 64bit
> / but have to save SKP back V2020 in order to import

Update to Sketchup 2021.1.279
https://github.com/RedHaloStudio/Sketchup_Importer/releases/tag/0.22.4

**Comment by arindam-m** [comment]
Check out this [release](https://github.com/arindam-m/pyslapi/releases/tag/v0.23.0) for Blender 2.93.x.
