### ISSUE TITLE
BUG !

### ISSUE THREAD

**Issue by 12745120333333333** [arindam-m/pyslapi#33]
**Describe the bug**
I am not able to choose the file and i am not able to click the check button 
**To Reproduce**
3. See error (if any) 'Error Log: ....'

**Expected behavior**

**Screenshots**
[To attach a file to an issue, drag and drop it into the comment box]

**System Info**
 - Operating System: [e.g. Windows 10]
 - Blender Version [e.g. 2.82a] (Only official releases)
 - SketchUp Version [e.g. 2019]
 - Importer Version [eg. v.0.20.2]

**Additional context**

**Comment by arindam-m** [comment]
Insufficient info (about the bug or the issue you might be facing).
