### ISSUE TITLE
Sketchup to Blender Import Error

### ISSUE THREAD

**Issue by jdkoll66** [arindam-m/pyslapi#4]
**Describe the bug**
Importing Sketchup model to Blender results in only cameras (Scenes) being imported.

**To Reproduce**
1. Go to 'File>Import'
2. Click on 'Import Sketchup Scene'
3. Error log
```
Traceback (most recent call last):
  File "C:\Users\jdkoll\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 886, in execute
    context, **keywords)
  File "C:\Users\jdkoll\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 185, in load
    self.write_duplicateable_groups()
  File "C:\Users\jdkoll\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 245, in write_duplicateable_groups
    group=group)
  File "C:\Users\jdkoll\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 640, in conponent_def_as_group
    group=group)
  File "C:\Users\jdkoll\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 613, in conponent_def_as_group
    self.context.scene.objects.link(ob)
AttributeError: 'bpy_prop_collection' object has no attribute 'link'
```

**Expected behavior**
Import of Sketchup geometry to Blender 2.83

**Screenshot**
![Sketchup to Blender Import](https://user-images.githubusercontent.com/45979057/85791370-b18dd700-b6ff-11ea-9a7c-7c663c77ba8b.PNG)

**System Info**
 - Operating System: Windows 10
 - Blender Version 2.83
 - SketchUp Version 19.3.253 64-bit
 - Importer Version v21.0

**Comment by arindam-m** [comment]
Grab the hot-fix version v0.21.1 from the same [release link](https://github.com/arindam-m/pyslapi/releases/tag/0.21).

**Comment by jdkoll66** [comment]
Hi,
Just installed the update. Unfortunately it didn't resolve the issue.
Here's the log:
bpy.context.space_data.system_bookmarks_active = 3Modules Installed (SketchUp_Importer) from 'D:\\Downloads\\SketchUp_Importer_v0.21.1_Windows_x64.zip' into 'C:\\Users\\jdkoll\\AppData\\Roaming\\Blender Foundation\\Blender\\2.83\\scripts\\addons'bpy.ops.object.delete(use_global=False, confirm=False)Deleted 1 object(s)bpy.context.space_data.recent_folders_active = 1bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(53.1297, 237.035, 120.404))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(324.796, -72.7086, 99.0893))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(244.181, -3.89881, 28.4982))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(178.826, -18.3061, 43.7425))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(229.046, 3.58768, 25.0366))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(193.843, 84.904, 17.3518))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(193.209, 51.3465, 15.8932))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(238.115, 8.52947, 25.5384))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(204.046, 34.2465, 10.1464))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(207.354, 61.4725, 3.48364))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(206.608, 54.3345, 3.11656))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(208.439, 38.2136, 4.02783))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(207.072, 65.5289, 6.50469))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(229.652, 11.0575, 16.2586))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(163.907, -19.3743, 42.4901))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(169.298, 66.0088, 29.8945))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(174.126, 56.9201, 23.9455))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(183.592, 71.4587, 18.3288))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(176.242, 72.6404, 23.3652))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(184.188, 61.2969, 27.999))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(179.647, 50.0984, 18.2937))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(220.633, 60.9159, 31.035))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(264.664, 56.1814, 30.193))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(244.933, 89.4163, 22.4154))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(226.344, 85.8547, 6.3781))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(264.846, 1.82934, 50.8668))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(242.786, 69.0263, 26.9541))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(252.731, 50.0652, 14.1643))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(202.917, 65.9949, 7.68832))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(167.985, 18.1119, 16.6343))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(201.486, 59.391, 8.68851))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(203.45, 36.4343, 8.62504))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(218.844, 78.3086, 18.9484))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(161.812, 12.0635, 19.4621))Traceback (most recent call last):  File "C:\Users\jdkoll\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 886, in execute    context, **keywords)  File "C:\Users\jdkoll\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 185, in load    self.write_duplicateable_groups()  File "C:\Users\jdkoll\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 245, in write_duplicateable_groups    group=group)  File "C:\Users\jdkoll\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 614, in conponent_def_as_group    ob.layers = 18 * [False] + [True] + [False]AttributeError: 'Object' object has no attribute 'layers'
location: <unknown location>:-1
bpy.ops.object.select_all(action='SELECT')bpy.ops.object.delete(use_global=False, confirm=False)Deleted 37 object(s)bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(53.1297, 237.035, 120.404))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(324.796, -72.7086, 99.0893))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(244.181, -3.89881, 28.4982))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(178.826, -18.3061, 43.7425))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(229.046, 3.58768, 25.0366))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(193.843, 84.904, 17.3518))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(193.209, 51.3465, 15.8932))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(238.115, 8.52947, 25.5384))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(204.046, 34.2465, 10.1464))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(207.354, 61.4725, 3.48364))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(206.608, 54.3345, 3.11656))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(208.439, 38.2136, 4.02783))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(207.072, 65.5289, 6.50469))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(229.652, 11.0575, 16.2586))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(163.907, -19.3743, 42.4901))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(169.298, 66.0088, 29.8945))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(174.126, 56.9201, 23.9455))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(183.592, 71.4587, 18.3288))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(176.242, 72.6404, 23.3652))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(184.188, 61.2969, 27.999))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(179.647, 50.0984, 18.2937))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(220.633, 60.9159, 31.035))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(264.664, 56.1814, 30.193))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(244.933, 89.4163, 22.4154))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(226.344, 85.8547, 6.3781))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(264.846, 1.82934, 50.8668))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(242.786, 69.0263, 26.9541))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(252.731, 50.0652, 14.1643))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(202.917, 65.9949, 7.68832))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(167.985, 18.1119, 16.6343))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(201.486, 59.391, 8.68851))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(203.45, 36.4343, 8.62504))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(218.844, 78.3086, 18.9484))bpy.ops.object.add(type='CAMERA', enter_editmode=False, align='WORLD', location=(161.812, 12.0635, 19.4621))Traceback (most recent call last):  File "C:\Users\jdkoll\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 886, in execute    context, **keywords)  File "C:\Users\jdkoll\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 185, in load    self.write_duplicateable_groups()  File "C:\Users\jdkoll\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 245, in write_duplicateable_groups    group=group)  File "C:\Users\jdkoll\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 640, in conponent_def_as_group    group=group)  File "C:\Users\jdkoll\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SketchUp_Importer\__init__.py", line 614, in conponent_def_as_group    ob.layers = 18 * [False] + [True] + [False]AttributeError: 'Object' object has no attribute 'layers'
location: <unknown location>:-1


    On Friday, June 26, 2020, 05:48:26 AM EDT, Arindam Mondal <notifications@github.com> wrote:  
 
 


Grab the hot-fix version v0.21.1 from the same release link.

**Comment by arindam-m** [comment]
This is why I ask for a sample of your file, where I can reproduce the same issue you are facing on your system.

If you can provide me with one such file, please do.

**Comment by arindam-m** [comment]
Please provide a sample of your file. I need to reproduce this issue on my system to fix it properly.

**Comment by jdkoll66** [comment]
Here's a link to the file. I was able to import a smaller file. Maybe size is the issue?
Thanks in advance!

https://tgwgroup-my.sharepoint.com/:u:/g/personal/jdkoll_tgw-group_com/ER0XdQjuYq1Kv3qvNU8YNgYB4BfUFDwns36zx-BJkQ8DPw?email=reply%2BAK6ZLMLSWBCCTGHPEG37VWF5BBOGTEVBNHHCM7ULXI%40reply.github.com&e=CJHqT9
    On Wednesday, July 1, 2020, 08:02:52 AM EDT, Arindam Mondal <notifications@github.com> wrote:  
 
 


Please provide a sample of your file. I need to reproduce this issue on my system to fix it properly.

**Comment by jdkoll66** [comment]
a { color: #0072bc; text-decoration: none; }






    
    
    
    
    Time of Access






  Time of Access v2
  
  
  

table td {border-collapse:collapse;margin:0;padding:0;}










 











 


 








 
 
 


 
Hello,


 
For security purposes, you must enter the code below to verify your account to access Burns & McDonnel (Jasco)_Composite_6-25-20_1000V3_Cleaned.skp. The code will only work for 15 minutes and if you request a new code, this code will stop working.


 




Account verification code:


59989179






 
Having problems with the code?


 
View the error and make sure that the email identifier is "7NW8DRC". If it's not, look for an updated email or try requesting a new code.








 


 

© 2017 Microsoft   Privacy & Cookies

**Comment by arindam-m** [comment]
I didn’t get enough time last week to work on this issue particularly as I was totally engaged in other things.

However, if you increase the threshold of “Instantiate When Similar Objects Are Over” to something like 1 million (which is 50 by default, under Primary Import Options), you will be able to import your SketchUp file.

**Comment by jdkoll66** [comment]
Your suggestion solved the problem. Thanks!
